### ISSUE TITLE
[Question]: ANDROID - Session timing out

### ISSUE THREAD

**Issue by boulaycote** [supabase-community/supabase-kt#229] opened 2023-07-11 17:50 UTC
### General info

- [X] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/wiki/Troubleshooting) page for similar problems

### What is your question?

Hi,

Thank you for this great lib. I really enjoy using it and it's super reliable. I have but a simple question:

It seems like my session is timing out if either postgresChangeFlow and broadcastFlow do not receive any updates for a while. Is it possible?
One thing I am doing that I am not sure is correct, I am login in using the same user on Web and on Android at the same time - to share user id and update values in db for that user - would that prevent the session being refreshed?

Thank you

**Comment by jan-tennert** [comment] 2023-07-11 17:57
Hey, what do you mean by "timeout"? Do you mean the session may expire, causing the client to not receive any updates?
Also, being logged in to the same account twice shouldn't be a problem. Do you have logging enabled? Maybe there are some useful logs to see.

**Comment by boulaycote** [comment] 2023-07-11 18:11
The client does not receive updates anymore is exactly what is happening. Unfortunately I don't have logs enabled. I see sometimes the subscription CLOSED on web, wondering if something similar might be happening on Android. Also, that's for an app that is deployed with version 0.9.5-dev-1. May not be relevant anymore?

Thanks for answering my question about the user log in.

**Comment by jan-tennert** [comment] 2023-07-11 18:14
> The client does not receive updates anymore is exactly what is happening. Unfortunately I don't have logs enabled. I see sometimes the subscription CLOSED on web, wondering if something similar might be happening on Android. Also, that's for an app that is deployed with version 0.9.5-dev-1. May not be relevant anymore?
> 
> Thanks for answering my question about the user log in.

No problem, looking through the code I think I may have found a problem causing Realtime to not update the JWT when the session expires, will publish a fix for that!

**Comment by k0shk0sh** [comment] 2023-07-12 06:57
I can confirm this as well, an app restart (fully restart) usually fixes the issue.

**Comment by jan-tennert** [comment] 2023-07-12 07:24
Yea this happening because the JWT update message doesnt get sent properly. A restart refreshes the session before connecting. Will publish a fix later this day.

**Comment by jan-tennert** [comment] 2023-07-12 16:02
Should hopefully be fixed in `1.1.1`, let me know if there are any issues left!

**Closed by jan-tennert** 2023-07-12 16:02 UTC
Labels: question

**Comment by boulaycote** [comment] 2023-07-13 18:50
Hi yes this works!

Thanks a bunch @jan-tennert for prompt answer and solution, once again.
